######################################################################
# @author      : xander (xander@xander-MS-7B49)
# @file        : Makefile
# @created     : Sunday Nov 17, 2019 12:01:40 PST
######################################################################

test : test.cpp point.cpp quadrilateral.cpp trapezoid.cpp equals.cpp parallelogram.cpp rectangle.cpp square.cpp
	g++ -c equals.cpp
	g++ -c test.cpp
	g++ -c point.cpp
	g++ -c quadrilateral.cpp
	g++ -c trapezoid.cpp
	g++ -c parallelogram.cpp
	g++ -c rectangle.cpp
	g++ -c square.cpp
	g++ -o test test.o equals.o point.o quadrilateral.o trapezoid.o parallelogram.o rectangle.o square.o
