######################################################################
# @author      : root (root@xander-MS-7B49)
# @file        : Makefile
# @created     : Sunday Nov 03, 2019 14:07:30 PST
######################################################################

test : test.cpp employee.cpp ProductionWorker.cpp
	g++ -c test.cpp
	g++ -c employee.cpp
	g++ -c ProductionWorker.cpp
	g++ -o test test.o employee.o ProductionWorker.o
	rm *.o
